export const UserRole = Object.freeze({
  CEO: 1,
  HEAD_OF_DEPARTMENT: 2,
  APPLICANT: 3,
  FINANCE: 4,
  ACCOUNTANT: 5,
});

export const BudgetingStatus = Object.freeze({
  DRAFT: 1,
  PENDING_LEAD_APPROVAL: 2,
  LEAD_DECLINED: 3,
  NEEDS_REVISION: 4,
  PENDING_FINANCE_APPROVAL: 5,
  FINANCE_DECLINED: 6,
  FINANCE_APPROVED: 7,
  PENDING_CEO_APPROVAL: 8,
  CEO_APPROVED: 9,
  CEO_DECLINED: 10,
});

export const FinancialRequestStatus = Object.freeze({
  DRAFT: 1,
  PENDING_APPROVAL: 2,
  NEEDS_REVISION: 3,
  SENT_TO_PAYMENT: 4,
  ACCOUNTANT_PAID: 5,
  ACCOUNTANT_PAID_AWAITING_DOCUMENTS: 6,
  FINANCE_CANCELED: 14,
  ACCOUNTANT_CANCELED: 20,
  FINANCE_PAID: 21,
  FINANCE_PAID_AWAITING_DOCUMENTS: 22,
});
