export const periodOptions = [
  { label: '1 міс', value: '1 міс' },
  { label: '2 міс', value: '2 міс' },
  { label: '3 міс', value: '3 міс' },
  { label: '4 міс', value: '4 міс' },
  { label: '5 міс', value: '5 міс' },
  { label: '6 міс', value: '6 міс' },
  { label: '7 міс', value: '7 міс' },
  { label: '8 міс', value: '8 міс' },
  { label: '9 міс', value: '9 міс' },
  { label: '10 міс', value: '10 міс' },
  { label: '11 міс', value: '11 міс' },
  { label: '12 міс', value: '12 міс' },
  { label: '24 міс', value: '24 міс' },
  { label: '36 міс', value: '36 міс' },
];
