export const periodOptions = [
  { label: '1 міс', value: '1 міс', labelKey: 'paymentPeriods.1' },
  { label: '2 міс', value: '2 міс', labelKey: 'paymentPeriods.2' },
  { label: '3 міс', value: '3 міс', labelKey: 'paymentPeriods.3' },
  { label: '4 міс', value: '4 міс', labelKey: 'paymentPeriods.4' },
  { label: '5 міс', value: '5 міс', labelKey: 'paymentPeriods.5' },
  { label: '6 міс', value: '6 міс', labelKey: 'paymentPeriods.6' },
  { label: '7 міс', value: '7 міс', labelKey: 'paymentPeriods.7' },
  { label: '8 міс', value: '8 міс', labelKey: 'paymentPeriods.8' },
  { label: '9 міс', value: '9 міс', labelKey: 'paymentPeriods.9' },
  { label: '10 міс', value: '10 міс', labelKey: 'paymentPeriods.10' },
  { label: '11 міс', value: '11 міс', labelKey: 'paymentPeriods.11' },
  { label: '12 міс', value: '12 міс', labelKey: 'paymentPeriods.12' },
  { label: '24 міс', value: '24 міс', labelKey: 'paymentPeriods.24' },
  { label: '36 міс', value: '36 міс', labelKey: 'paymentPeriods.36' },
];
